services:


  mongodb:
    image: mongo:7.0.0 # Используем официальный образ MongoDB
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: eKOM  # Имя базы данных по умолчанию
    ports:
      - "27017:27017"
    volumes:
      - mongo_vol:/data/db  # Монтируем том для хранения данных MongoDB
    networks:
      - backend
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
#    environment:
#      - MONGODB_URL=mongodb://mongodb:27017/e_kom  # Update to use service name
    networks:
      - backend
volumes:
  mongo_vol: { }

networks:
  backend: