services:
#  fastapi:
#    build:
#      context: ./app  # Путь к директории с вашим приложением
#      dockerfile: Dockerfile
#    container_name: fastapi_app
#    restart: unless-stopped
#    environment:
#      MONGODB_DATABASE: flaskdb
#      MONGODB_USERNAME: flaskuser
#      MONGODB_PASSWORD: your_mongodb_password
#      MONGODB_HOSTNAME: mongodb
#    ports:
#      - "8000:80"  # Прокидываем порт 80 контейнера на порт 8000 хоста
#    depends_on:
#      - mongodb  # Указывает, что контейнер fastapi зависит от mongodb
#    networks:
#      - backend

  mongodb:
    image: mongo:7.0.0 # Используем официальный образ MongoDB
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: eKOM  # Имя базы данных по умолчанию
    ports:
      - "27017:27017"
    volumes:
      - mongo_vol:/data/db  # Монтируем том для хранения данных MongoDB
    networks:
      - backend

volumes:
  mongo_vol: {}

networks:
  backend: